name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for `git describe` to work correctly

      - name: Get Latest Tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")
          echo "::set-output name=tag::$TAG"
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        env:
          GIT_TAG: ${{ steps.get_tag.outputs.tag }} # Expose to build process, if needed
        run: npm run build

      - name: Export Next.js app (if using static export)
        run: npm run export # Only if you're using `next export`

      - name: Create version.js
        run: |
          VERSION="${{ steps.get_tag.outputs.tag }}"
          echo "export const version = '$VERSION';" > ./out/version.js
        shell: bash

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: your-firebase-project-id
          target: your-firebase-target
