name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for please-release

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your desired Node.js version

      - name: Install dependencies
        run: npm ci # Or yarn install, pnpm install

      - name: Run tests
        run: npm test # Or yarn test, pnpm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Important!
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Or your NPM or other package registry token
        run: npx please-release
