name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this line!
      pull-requests: write # also good to explicitly include
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node # Or 'java', 'python', etc., depending on your project
          package-name: your-package-name # Optional: Required for some release types. Omit if not a monorepo.
          token: ${{ secrets.GITHUB_TOKEN }}
